//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.Diagramming.SoftwareArchitectureShapes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dataweb.Diagramming.SoftwareArchitectureShapes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] Actor {
            get {
                object obj = ResourceManager.GetObject("Actor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Actor_new {
            get {
                object obj = ResourceManager.GetObject("Actor_new", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Icon Dataweb_Diagramming {
            get {
                object obj = ResourceManager.GetObject("Dataweb_Diagramming", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static byte[] Monitor {
            get {
                object obj = ResourceManager.GetObject("Monitor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Monitor_new1 {
            get {
                object obj = ResourceManager.GetObject("Monitor_new1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Monitor_old {
            get {
                object obj = ResourceManager.GetObject("Monitor_old", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PC {
            get {
                object obj = ResourceManager.GetObject("PC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PC2 {
            get {
                object obj = ResourceManager.GetObject("PC2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PC21 {
            get {
                object obj = ResourceManager.GetObject("PC21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PC3 {
            get {
                object obj = ResourceManager.GetObject("PC3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] RTU {
            get {
                object obj = ResourceManager.GetObject("RTU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Tower {
            get {
                object obj = ResourceManager.GetObject("Tower", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
